// ============================================================================
// VERIRAG ACTION LAYER (Intent Detection, Drafting & GitHub Issue Creator)
// ============================================================================

import 'dotenv/config';
import Groq from 'groq-sdk';
import { Octokit } from '@octokit/rest';
import * as readline from 'readline';
import { hybridSearch, SearchResult } from './retrieve.js';
import { evaluateFaithfulness } from './judge.js';
import { askQuestion } from './rag.js';

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

export interface IssueDraft {
  isActionIntent: boolean;
  title: string;
  body: string;
  labels: string[];
}

/**
 * 1. INTENT CLASSIFIER & ISSUE DRAFTER
 */
export async function classifyAndDraftAction(query: string, contextChunks: SearchResult[]): Promise<IssueDraft> {
  const context = contextChunks.map((c) => `[Source: ${c.id}]\n${c.content}`).join('\n\n');

  const draftPrompt = `You are the action planner for VeriRAG.
    Analyze the user's prompt to determine if they intend to file a bug report, ticket, or GitHub issue.

    CONTEXT:
    ${context}

    USER PROMPT:
    ${query}

    Instructions:
    1. If the user is NOT requesting an action (just asking a question), set "isActionIntent": false.
    2. If the user IS requesting an action, set "isActionIntent": true and generate a concise issue title and a well-structured markdown body.
    3. The issue body MUST reference the technical specifics found in CONTEXT (e.g., status codes, metrics, ports).

    Return valid JSON matching this schema:
    {
      "isActionIntent": boolean,
      "title": "Clear issue title",
      "body": "Markdown issue body summarizing technical context and reproduction steps",
      "labels": ["bug" | "documentation" | "enhancement"]
    }`;

  try{
    const completion = await groq.chat.completions.create({
    model: 'openai/gpt-oss-120b',
    messages: [
      { role: 'system', content: 'Respond ONLY with valid JSON.' },
      { role: 'user', content: draftPrompt }
    ],
    temperature: 0.1,
    response_format: { type: 'json_object' }
  });

    return JSON.parse(completion.choices[0]?.message?.content || '{}') as IssueDraft;
  } catch(err: any) {

    // Intercept safety refusals, JSON validation errors, or HTTP 400s cleanly as an action rejection
    const isSafetyRefusal =
      err?.error?.error?.code === 'json_validate_failed' ||
      err?.status === 400 ||
      err?.message?.includes('json_validate_failed') ||
      err?.error?.error?.failed_generation?.includes("can't help");
    
    if (isSafetyRefusal) {
      return {
        isActionIntent: false,
        title: '',
        body: 'Action blocked by safety policy or invalid action intent.',
        labels: []
      };
    }
    
    return {
      isActionIntent: false,
      title: '',
      body: '',
      labels: []
    };
  }
}

/**
 * 2. DISPATCH ISSUE TO GITHUB (Used by both API and CLI)
 */
export async function dispatchGitHubIssue(draft: { title: string; body: string; labels?: string[] }): Promise<string> {
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;

  if (!process.env.GITHUB_TOKEN || !owner || !repo) {
    console.log('\n⚠️ [DRY-RUN MODE]: GITHUB_TOKEN or GITHUB_OWNER/REPO not set in .env.');
    return `https://github.com/example/mock-repo/issues/${Math.floor(Math.random() * 1000)}`;
  }

  const res = await octokit.issues.create({
    owner,
    repo,
    title: draft.title,
    body: `${draft.body}\n\n---\n*Auto-generated by VeriRAG Knowledge Assistant (Grounded & Verified)*`,
    labels: draft.labels || ['verirag-action'],
  });

  return res.data.html_url;
}

/**
 * 3. HUMAN-IN-THE-LOOP (HITL) CLI PROMPT
 */
async function promptConfirmation(promptText: string): Promise<boolean> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise((resolve) => {
    rl.question(`\n⚠️  ${promptText} (y/N): `, (answer) => {
      rl.close();
      resolve(answer.trim().toLowerCase() === 'y');
    });
  });
}

/**
 * CLI EXECUTOR RUNNER
 */
export async function executeGatedAction(query: string): Promise<void> {
  console.log(`🔎 Retrieving context for query: "${query}"...`);
  const chunks = await hybridSearch(query, 3);

  const draft = await classifyAndDraftAction(query, chunks);

  if (!draft.isActionIntent) {
    console.log('ℹ️ No action intent detected. Handing over to standard Q&A.');
    const response = await askQuestion(query, 3);
    console.log('\n💬 ANSWER:\n' + response.answer);
    console.log(`\n⚖️ VERIFICATION: ${response.verification.isFaithful ? '✅ PASS' : '❌ FAIL'}`);
    return;
  }

  console.log('\n📝 Drafted GitHub Issue:');
  console.log(`📌 Title:  ${draft.title}`);
  console.log(`🏷️ Labels: ${draft.labels.join(', ')}`);
  console.log(`📄 Body:\n${draft.body}\n`);

  console.log('⚖️  Running Judge Gate to verify groundedness before action execution...');
  const combinedText = `${draft.title}\n${draft.body}`;
  const verification = await evaluateFaithfulness(query, chunks, combinedText);

  if (!verification.isFaithful || verification.confidenceScore < 0.7) {
    console.log('\n🛑 ACTION BLOCKED BY JUDGE GATE');
    console.log(`Reason: ${verification.reasoning}`);
    return;
  }
  console.log(`✅ Judge Gate Passed! (Confidence: ${(verification.confidenceScore * 100).toFixed(0)}%)`);

  const confirmed = await promptConfirmation('Do you confirm dispatching the issue to GitHub?');
  if (!confirmed) {
    console.log('❌ Action aborted by user.');
    return;
  }

  const issueUrl = await dispatchGitHubIssue(draft);
  console.log(`\n🎉 Success! Issue created at: ${issueUrl}`);
}

async function run() {
  const cliArgs = process.argv.slice(2).join(' ').trim();
  const query = cliArgs || 'File an issue: Downstream service returning 503 errors during open circuit state.';
  await executeGatedAction(query);
}

if (process.argv[1] && process.argv[1].endsWith('action.ts')) {
  run();
}